name: CI
#  This workflow is run on pushes to main & every Pull Requests except changes to tools/interop-node.
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        go-arch: [amd64, arm64]
        include:
          - go-arch: amd64
            os: ubuntu-latest
          - go-arch: arm64
            os: macos-13-xlarge
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: ${{ always() && (needs.lint.result == 'success' || needs.test.result == 'success') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile
            .github/workflows/build.yml
      - name: Download Go Dependency
        if: env.GIT_DIFF
        run : go mod download
      - name: Build
        if: env.GIT_DIFF
        run: GOOS=linux GOARCH=${{ matrix.go-arch }} make build
